/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Proxy;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAM$
 */
public class Post extends javax.swing.JFrame {

    /**
     * Creates new form Post
     */
    
    private final dbUsers db;
    private final Client client;
    private ArrayList<ArrayList<String>> Posts;
    
    public Post(Client cliente) {
        initComponents();
        
        client = cliente;
        db = new dbUsers();
        db.connectDataBase();
        getPosts();
        setLocationRelativeTo(null);
        Color containerColor = new Color(111,168,162);
        Color headerColor = new Color(111,168,162);
        Color content = new Color(111,168,162);
        getContentPane().setBackground(content);
        
    }
    
    private void getPosts(){
        DefaultTableModel modelo = (DefaultTableModel) tablePosts.getModel();
        int filas = tablePosts.getModel().getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
        Posts = db.getPosts(client.getUser());
        //DefaultTableModel modelo = (DefaultTableModel) tablePosts.getModel();
        Object x[];
        x = new Object[3];
        for(ArrayList<String> post:Posts){
            String user = db.getClient(db.getUsername(Integer.parseInt(post.get(0))))[1];
            String comment = post.get(1);
            String imagen = post.get(2);
            
            //System.out.println("User: "+user+"\nComment: "+comment+"\nImagen: "+imagen);
            
            x[0] = user;
            x[1] = comment;
            x[2] = imagen;
            modelo.addRow(x);
            
           // tablePosts.setValueAt(newIcon, i-1, 2);
        }
        
        tablePosts.getColumnModel().getColumn(2).setCellRenderer(new ImageRenderer());
        tablePosts.setModel(modelo);
        tablePosts.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmImagen = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        btnImagen = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPost = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePosts = new javax.swing.JTable();
        btnLike = new javax.swing.JButton();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\JAM$\\Pictures"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmImagenLayout = new javax.swing.GroupLayout(frmImagen.getContentPane());
        frmImagen.getContentPane().setLayout(frmImagenLayout);
        frmImagenLayout.setHorizontalGroup(
            frmImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmImagenLayout.setVerticalGroup(
            frmImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(111, 168, 162));

        btnImagen.setBackground(new java.awt.Color(43, 128, 125));
        btnImagen.setFont(new java.awt.Font("Futura", 1, 13)); // NOI18N
        btnImagen.setForeground(new java.awt.Color(255, 255, 192));
        btnImagen.setText("Subir Imagen");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        btnPost.setBackground(new java.awt.Color(43, 128, 125));
        btnPost.setFont(new java.awt.Font("Futura", 1, 13)); // NOI18N
        btnPost.setForeground(new java.awt.Color(255, 255, 192));
        btnPost.setText("Publicar Post");
        btnPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPostMouseClicked(evt);
            }
        });
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        txtPost.setColumns(20);
        txtPost.setFont(new java.awt.Font("Futura", 0, 13)); // NOI18N
        txtPost.setRows(5);
        jScrollPane1.setViewportView(txtPost);

        btnSalir.setBackground(new java.awt.Color(43, 128, 125));
        btnSalir.setFont(new java.awt.Font("Futura", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 192));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablePosts.setFont(new java.awt.Font("Futura", 1, 12)); // NOI18N
        tablePosts.setForeground(new java.awt.Color(0, 51, 0));
        tablePosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Comentario", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePosts.setRowHeight(78);
        tablePosts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePostsMouseClicked(evt);
            }
        });
        tablePosts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablePostsKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablePosts);

        btnLike.setBackground(new java.awt.Color(43, 128, 125));
        btnLike.setFont(new java.awt.Font("Futura", 1, 13)); // NOI18N
        btnLike.setForeground(new java.awt.Color(255, 255, 192));
        btnLike.setText("Me Gusta");
        btnLike.setEnabled(false);
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPost))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        this.btnImagen.setText(jFileChooser1.getSelectedFile().getPath());
        frmImagen.setVisible(false);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        frmImagen.setSize(540, 315);
        frmImagen.setLocationRelativeTo(null);
        frmImagen.setVisible(true);
    }//GEN-LAST:event_btnImagenActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        String imagen = "";
        if (!btnImagen.getText().equals("Subir Imagen")) {
            imagen = jFileChooser1.getSelectedFile().getPath();
        }
        if(!txtPost.getText().isEmpty()){
            if (db.Post(client.getID(), txtPost.getText(), imagen) != -1) {
                txtPost.setText("");
                btnImagen.setText("Subir Imagen");
                getPosts();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo realizar el Post!\n");
        }
    }//GEN-LAST:event_btnPostActionPerformed

class ImageRenderer extends DefaultTableCellRenderer {
  JLabel lbl = new JLabel();

  @Override
  public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
    boolean hasFocus, int row, int column) {
    //lbl.setText((String) value);
    ImageIcon ic = new ImageIcon((String) value);
    Image img = ic.getImage();
    int ancho = Math.abs(ic.getIconWidth() - Math.abs(ic.getIconHeight()-78));
    BufferedImage bi = new BufferedImage(ancho, 78, BufferedImage.TYPE_INT_ARGB);
    Graphics g = bi.createGraphics();
    g.drawImage(img, 0, 0, ancho, 78, null);
    ImageIcon newIcon = new ImageIcon(bi);
            
            
    lbl.setIcon(newIcon);
    return lbl;
  }
}

    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        int row = tablePosts.getSelectedRow();
        String comment = tablePosts.getValueAt(row, 1).toString();
        int usuario = db.getClientid(tablePosts.getValueAt(row, 0).toString());
        String imagen = tablePosts.getValueAt(row, 2).toString();
        
        if (db.likeComment(usuario, comment, imagen) != -1) {
            btnLike.setEnabled(false);
        }
    }//GEN-LAST:event_btnLikeActionPerformed

    private void tablePostsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePostsMouseClicked
        getLike();
    }//GEN-LAST:event_tablePostsMouseClicked

    private void tablePostsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablePostsKeyPressed
        getLike();
    }//GEN-LAST:event_tablePostsKeyPressed

    private void btnPostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostMouseClicked
    
    }//GEN-LAST:event_btnPostMouseClicked

    private void getLike(){
        int row = tablePosts.getSelectedRow();
        String comment = tablePosts.getValueAt(row, 1).toString();
        int usuario = db.getClientid(tablePosts.getValueAt(row, 0).toString());
        
        if (db.getLikeComment(usuario, client.getID(), comment) > 0) {
            btnLike.setEnabled(false);
        }else{
            btnLike.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFrame frmImagen;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablePosts;
    private javax.swing.JTextArea txtPost;
    // End of variables declaration//GEN-END:variables
}
